import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://worthy-embrace-production-9664.up.railway.app/');
  await page.getByRole('checkbox', { name: 'Ajouter' }).nth(1).check();
  await page.getByRole('checkbox', { name: 'Ajouter' }).nth(1).check();
  await page.getByRole('link', { name: 'Continuer' }).click();
  await page.locator('input[name="nomPrenom"]').click();
  await page.locator('input[name="nomPrenom"]').press('CapsLock');
  await page.locator('input[name="nomPrenom"]').fill('H');
  await page.locator('input[name="nomPrenom"]').press('CapsLock');
  await page.locator('input[name="nomPrenom"]').fill('Hadjoudj ');
  await page.locator('input[name="nomPrenom"]').press('CapsLock');
  await page.locator('input[name="nomPrenom"]').fill('Hadjoudj M');
  await page.locator('input[name="nomPrenom"]').press('CapsLock');
  await page.locator('input[name="nomPrenom"]').fill('Hadjoudj Malik');
  await page.locator('input[name="fonction"]').click();
  await page.locator('input[name="fonction"]').press('CapsLock');
  await page.locator('input[name="fonction"]').fill('A');
  await page.locator('input[name="fonction"]').press('CapsLock');
  await page.locator('input[name="fonction"]').fill('Agent commercial');
  await page.locator('input[name="raisonSociale"]').click();
  await page.locator('input[name="raisonSociale"]').press('CapsLock');
  await page.locator('input[name="raisonSociale"]').fill('MELEVEN');
  await page.locator('input[name="raisonSociale"]').press('CapsLock');
  await page.locator('input[name="adresse"]').click();
  await page.locator('input[name="adresse"]').press('CapsLock');
  await page.locator('input[name="adresse"]').fill('03');
  await page.locator('input[name="adresse"]').press('CapsLock');
  await page.locator('input[name="adresse"]').fill('03 ');
  await page.locator('input[name="adresse"]').press('CapsLock');
  await page.locator('input[name="adresse"]').fill('03 R');
  await page.locator('input[name="adresse"]').press('CapsLock');
  await page.locator('input[name="adresse"]').fill('03 Rue ');
  await page.locator('input[name="adresse"]').press('CapsLock');
  await page.locator('input[name="adresse"]').fill('03 Rue A');
  await page.locator('input[name="adresse"]').press('CapsLock');
  await page.locator('input[name="adresse"]').fill('03 Rue Ahmed sayeh');
  await page.locator('input[name="tel"]').click();
  await page.locator('input[name="adresse"]').press('CapsLock');
  await page.locator('input[name="tel"]').fill('0552667779');
  await page.locator('input[name="contact"]').click();
  await page.locator('input[name="contact"]').fill('S');
  await page.locator('input[name="contact"]').press('CapsLock');
  await page.locator('input[name="contact"]').fill('Sara');
  await page.locator('input[name="email"]').click();
  await page.locator('input[name="email"]').fill('malikhadjoudj');
  await page.locator('input[name="email"]').press('CapsLock');
  await page.locator('input[name="email"]').fill('malikhadjoudj3');
  await page.locator('input[name="email"]').press('CapsLock');
  await page.locator('input[name="email"]').fill('malikhadjoudj3@gmail;');
  await page.locator('input[name="email"]').press('CapsLock');
  await page.locator('input[name="email"]').fill('malikhadjoudj3@gmail;');
  await page.locator('input[name="email"]').press('CapsLock');
  await page.locator('input[name="email"]').fill('malikhadjoudj3@gmail');
  await page.locator('input[name="email"]').press('CapsLock');
  await page.locator('input[name="email"]').fill('malikhadjoudj3@gmail.');
  await page.locator('input[name="email"]').press('CapsLock');
  await page.locator('input[name="email"]').fill('malikhadjoudj3@gmail.com');
  await page.locator('input[name="email"]').press('CapsLock');
  await page.locator('input[name="rc"]').click();
  await page.locator('input[name="rc"]').fill('3455367367990864');
  await page.locator('input[name="nif"]').dblclick();
  await page.locator('input[name="nif"]').fill('345466764789064324464');
  await page.locator('input[name="art"]').click();
  await page.locator('input[name="art"]').fill('5');
  await page.locator('input[name="nif"]').click();
  await page.getByText('Le NIF doit contenir 20').click();
  await page.getByText('Le NIF doit contenir 20').click();
  await page.getByText('NIF :Le NIF doit contenir 20').click();
  await page.locator('input[name="nif"]').click();
  await page.locator('input[name="nif"]').fill('34566764789064324464');
  await page.locator('input[name="art"]').click();
  await page.locator('input[name="art"]').fill('55564467755');
  await page.locator('input[name="nis"]').click();
  await page.locator('input[name="nis"]').fill('4');
  await page.locator('input[name="nis"]').click();
  await page.locator('input[name="nis"]').fill('4545353467676783');
  await page.locator('input[name="activite"]').click();
  await page.locator('input[name="activite"]').fill('JSP');
  await page.locator('input[name="activite"]').press('CapsLock');
  await page.getByRole('button', { name: '✅ Valider maintenant' }).click();
  await page.locator('input[name="nis"]').click();
  await page.locator('input[name="nis"]').fill('454535346767678');
  await page.getByRole('button', { name: '✅ Valider maintenant' }).click();
  await page.locator('input[name="nomPrenom"]').click();
  await page.locator('input[name="nomPrenom"]').press('CapsLock');
  await page.locator('input[name="nomPrenom"]').fill('H');
  await page.locator('input[name="nomPrenom"]').press('CapsLock');
  await page.locator('input[name="nomPrenom"]').fill('Hadjoudj ');
  await page.locator('input[name="nomPrenom"]').press('CapsLock');
  await page.locator('input[name="nomPrenom"]').fill('Hadjoudj M');
  await page.locator('input[name="nomPrenom"]').press('CapsLock');
  await page.locator('input[name="nomPrenom"]').fill('Hadjoudj Malik');
  await page.locator('input[name="entreprise"]').click();
  await page.locator('input[name="entreprise"]').press('CapsLock');
  await page.locator('input[name="entreprise"]').fill('M');
  await page.locator('input[name="entreprise"]').press('CapsLock');
  await page.locator('input[name="entreprise"]').fill('M');
  await page.locator('input[name="entreprise"]').press('CapsLock');
  await page.locator('input[name="entreprise"]').fill('MELEVEN');
  await page.locator('input[name="entreprise"]').press('CapsLock');
  await page.getByRole('button', { name: '✅ Valider maintenant' }).click();
// On cherche juste la partie "BACK TO SCHOOL" sans se soucier des emojis ou des fautes
  
  await page.getByRole('heading', { name: 'ENGAGEMENT :' }).click();
  await page.getByText('Je soussigné(e) Mr/Mme : Hadjoudj Malik').click();
  await page.getByText('Je soussigné(e) Mr/Mme : Hadjoudj MalikReprésentant de l\'entreprise : MELEVENDé').click();
  await page.locator('div').filter({ hasText: 'édi1tionBACK TOSCHOOL✏️' }).nth(4).click();
  await page.getByText('MELEVEN AGENCYAdresse :').click();
  await page.locator('div').filter({ hasText: /^édi1tionBACK TOSCHOOL✏️$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: 'édi1tionBACK TOSCHOOL✏️' }).nth(4).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: '⬇️ PDF document 1' }).click();
  const download = await downloadPromise;
  const download1Promise = page.waitForEvent('download');
  await page.getByRole('button', { name: '⬇️ PDF document 2' }).click();
  const download1 = await download1Promise;
  await page.getByRole('button', { name: '🖨️ Imprimer / Sauvegarder en' }).click();
  await page.getByRole('link', { name: 'Passer au dépôt →' }).click();
  await page.getByText('Parcourir les fichiers').click();
  await page.getByLabel('Parcourir les fichiers').setInputFiles('Bon_de_commande_dsfsdf.pdf');
  await page.getByRole('button', { name: 'Soumettre le dossier' }).click();
  await page.getByRole('button', { name: 'Retour à l\'accueil' }).click();
  await page.goto('https://worthy-embrace-production-9664.up.railway.app/admin');
  await page.getByText('DOC...Contrats recus0%').click();
  await page.getByText('INS18Total inscrits').click();
  await page.getByText('DA16.2M DACA Previsionnel').click();
  await page.getByRole('button', { name: 'Contrats reçus' }).click();
  await page.getByRole('button', { name: 'En attente' }).click();
  await page.getByRole('button', { name: '✨ Standard' }).click();
  await page.getByRole('button', { name: '🚀 Expo Plus' }).click();
  await page.getByRole('button', { name: '🛍️ Espace Vente' }).click();
  await page.getByRole('button', { name: '📐 Espace Nu' }).click();
  await page.getByRole('button', { name: '🇮🇹 Pack Sponsor Italie' }).click();
  await page.getByRole('button', { name: '🇹🇷 Pack Sponsor Turquie' }).click();
  await page.getByRole('button', { name: '🇮🇹 Pack Sponsor Italie' }).click();
  await page.getByRole('button', { name: '🇹🇷 Pack Sponsor Turquie' }).click();
  await page.getByRole('button', { name: '🇩🇿 Pack Sponsor Algérie' }).click();
  await page.locator('div').filter({ hasText: /^Rech\.$/ }).click();
  await page.locator('div').filter({ hasText: /^Rech\.$/ }).click();
  await page.getByRole('button', { name: 'Contrats reçus' }).click();
  await page.getByRole('textbox', { name: 'Rechercher par nom...' }).click();
  await page.getByRole('textbox', { name: 'Rechercher par nom...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Rechercher par nom...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Rechercher par nom...' }).fill('');
  await page.getByRole('textbox', { name: 'Rechercher par nom...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Rechercher par nom...' }).fill('H');
  await page.getByRole('textbox', { name: 'Rechercher par nom...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Rechercher par nom...' }).fill('Hadjoudj ');
  await page.getByRole('textbox', { name: 'Rechercher par nom...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Rechercher par nom...' }).fill('Hadjoudj M');
  await page.getByRole('textbox', { name: 'Rechercher par nom...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Rechercher par nom...' }).fill('Hadjoudj Malik');
  await page.locator('div').filter({ hasText: /^Rech\.$/ }).click();
  await page.locator('div').filter({ hasText: /^Rech\.$/ }).click();
  await page.getByRole('textbox', { name: 'Rechercher par nom...' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Rechercher par nom...' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Rechercher par nom...' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Rechercher par nom...' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Rechercher par nom...' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Rechercher par nom...' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Rechercher par nom...' }).fill(' Malik');
  await page.locator('div').filter({ hasText: /^Rech\.$/ }).click();
  await page.getByRole('textbox', { name: 'Rechercher par nom...' }).fill('');
  await page.getByRole('button', { name: 'Voir' }).first().click();
  await page.getByText('Fonction').click();
  await page.getByText('Total HT999 000 DA').click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: '📥 Voir' }).click();
  const page1 = await page1Promise;
  await page.locator('div').filter({ hasText: '✕BON DE COMMANDEAperçu du' }).nth(3).click();
  await page.locator('div').filter({ hasText: '✕BON DE COMMANDEAperçu du' }).nth(3).click();
  await page.locator('div').filter({ hasText: '✕BON DE COMMANDEAperçu du' }).nth(3).click();
  await page.locator('div').filter({ hasText: '✕BON DE COMMANDEAperçu du' }).nth(3).click();
  await page.locator('div').filter({ hasText: '✕BON DE COMMANDEAperçu du' }).nth(3).click();
  await page.locator('div').filter({ hasText: '✕BON DE COMMANDEAperçu du' }).nth(3).dblclick();
  await page.goto('https://worthy-embrace-production-9664.up.railway.app/admin');
  await page.getByRole('button', { name: '+ Attribuer' }).first().click();
  await page.getByRole('button', { name: 'A5 25 m²' }).click();
  await page.getByRole('button', { name: 'A5 25 m²' }).click();
  await page.getByRole('button', { name: 'C3 50 m²' }).click();
  await page.getByRole('button', { name: '✕' }).click();
  await page.getByRole('link', { name: '🗺️ Plan de salle' }).click();
  await page.locator('g:nth-child(28) > rect').click();
  await page.getByRole('spinbutton').first().fill('2');
  await page.getByRole('spinbutton').first().press('CapsLock');
  await page.getByRole('spinbutton').first().fill('27');
  await page.getByRole('spinbutton').first().press('CapsLock');
  await page.goto('https://worthy-embrace-production-9664.up.railway.app/admin');
});